#!/usr/bin/env python

from setuptools import setup, find_packages
from subprocess import Popen, PIPE

def get_git_version():
    try:
        # Somehow git describe is confused if fakeroot is used. The command
        # below seems to work around that. I really don't have any clue :(
        Popen(['git', 'diff']).wait()
        p = Popen(['git', 'describe', '--tags', '--always', '--dirty'],
                stdout=PIPE, stderr=PIPE)
        p.stderr.close()
        if p.wait() == 0:
            return p.stdout.readlines()[0].strip()
    except:
        pass
    raise AssertionError('Could not find the version number')

def main():
    version = get_git_version()

    with open('pyipmi/version.py', 'w') as f:
        f.write('# This file was autogenerated by setup.py\n')
        f.write('__version__ = \'%s\'\n' % (version,))

    setup(name = 'pyipmi',
            version = version,
            description = 'Pure python IPMI library',
            author_email = 'michael.walle@kontron.com',
            packages = find_packages(exclude="test"),
            package_data = {
                'pyipmi.ext.totalphase':
                    ['aardvark.so', 'LICENSE.txt']
            },
            scripts = ['bin/ipmitool.py'],
            test_suite = 'tests',
    )

if __name__ == '__main__':
    main()
