#!/usr/bin/env python

from setuptools import setup, find_packages
import os
import re
import subprocess

name = 'python-ipmi'
version_py = os.path.join(os.path.dirname(__file__), 'pyipmi', 'version.py')


# filled in by 'git archive' (see .gitattributes), e.g. for the tarballs of
# the GitHub releases that contain neither the git repository nor version.py
version_archive = os.path.join(os.path.dirname(__file__), 'version_archive.txt')


def pep440_version(describe):
    """Convert the output of 'git describe' to a PEP 440 version.

    0.5.8-77-g7c853b0.dirty -> 0.5.8.dev77+g7c853b0.dirty

    Without tags, e.g. in a shallow clone, 'git describe --always' prints
    only the abbreviated commit:

    7c853b0.dirty -> 0+g7c853b0.dirty
    """
    m = re.match(r'^([0-9a-f]{7,40})(\.dirty)?$', describe)
    if m:
        commit, dirty = m.groups()
        return '0+g' + commit + (dirty or '')
    m = re.match(r'^(.+?)(?:-(\d+)-(g[0-9a-f]+))?(\.dirty)?$', describe)
    tag, distance, commit, dirty = m.groups()
    version = tag
    if distance:
        version += f'.dev{distance}+{commit}'
    if dirty:
        version += ('.' if distance else '+') + dirty[1:]
    return version


def git_version():
    return subprocess.check_output(
            ['git', 'describe', '--tags', '--always', '--dirty=.dirty'],
            stderr=subprocess.STDOUT).decode().strip()


def archive_version():
    with open(version_archive) as f:
        describe = f.read().strip()
    # not substituted, the file is not part of a 'git archive'
    if not describe or describe.startswith('$Format'):
        raise OSError(f'version not available in {version_archive}')
    return describe


def write_version_py(version):
    with open(version_py, 'w') as f:
        f.write('# This file was autogenerated by setup.py\n')
        f.write(f'__version__ = \'{version}\'\n')


try:
    version = pep440_version(git_version())
    write_version_py(version)
except (OSError, subprocess.CalledProcessError):
    try:
        with open(version_py) as f:
            d = dict()
            exec(f.read(), d)
            version = d['__version__']
    except OSError:
        try:
            version = pep440_version(archive_version())
            write_version_py(version)
        except OSError:
            # a valid PEP 440 version, otherwise setuptools refuses to build
            version = '0+unknown'


with open('README.md') as f:
    readme = f.read()

setup(name=name,
      version=version,
      description='Pure python IPMI library',
      long_description=readme,
      long_description_content_type='text/markdown',
      url='https://github.com/kontron/python-ipmi',
      download_url='https://github.com/kontron/python-ipmi/tarball/' + version,
      author='Michael Walle, Heiko Thiery',
      author_email='michael.walle@kontron.com, heiko.thiery@kontron.com',
      packages=find_packages(exclude=['tests*']),
      license='LGPLv2+',
      platforms=["any"],
      python_requires='>=3.10',
      classifiers=[
          'Development Status :: 3 - Alpha',
          'Environment :: Console',
          'License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)',
          'Natural Language :: English',
          'Operating System :: OS Independent',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.10',
          'Programming Language :: Python :: 3.11',
          'Programming Language :: Python :: 3.12',
          'Programming Language :: Python :: 3.13',
          'Programming Language :: Python :: 3.14',
          'Topic :: Software Development :: Libraries :: Python Modules',
      ],
      entry_points={
          'console_scripts': [
              'ipmitool.py = pyipmi.ipmitool:main',
          ]
      },
      test_suite='tests',
      tests_require=[
          'pytest',
      ],
      install_requires=[
      ],
      extras_require={
          'rmcpplus': ['cryptography'],
      },
      )
