# entity types
ENTITY_TYPE_POWER_MODULE = 0x0a
ENTITY_TYPE_COOLING_UNIT = 0x1e
ENTITY_TYPE_PICMG_FRONT_BOARD = 0xa0
ENTITY_TYPE_PICMG_REAR_TRANSITION_MODULE = 0xc0
ENTITY_TYPE_PICMG_ADVANCED_MC = 0xc1
ENTITY_TYPE_PICMG_MICROTCA_CARRIER_HUB = 0xc2
ENTITY_TYPE_PICMG_SHELF_MANAGEMENT_CONTROLLER = 0xf0
ENTITY_TYPE_PICMG_FILTRATION_UNIT = 0xf1
ENTITY_TYPE_PICMG_SHELF_FRU_INFORMATION = 0xf2

