name: Check DCO

on: [push, pull_request, workflow_dispatch]

jobs:
  check-dco:
    name: Check Developer's Certificate of Origin
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -U dco-check
          dco-check

