name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  ruff:
    name: Lint with ruff
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install ruff==0.16.10

      - name: Lint with ruff
        run: ruff check --output-format=github .

  codespell:
    name: Check spelling with codespell
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install codespell

      - name: Check spelling
        run: codespell
